#!/bin/bash
# Copyright (C) 2018-2019 Andreas Huber Dönni
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program. If not, see
# <http://www.gnu.org/licenses/>.

set -o errexit
set -o nounset
set -o pipefail

pushd $(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

echo "Bumping version..."
VERSION=`npm version patch -m "Publish v%s"`
echo "Building..."
rm -rf dist
npm run build
echo "Pushing sources..."
git push
git push --tags

popd
